Repository kedacore/keda, pull requests merged in 2022-07, with the labels that each got.

#3342 Fix path in ARM test script.
  tests/run-arm-smoke-tests.sh
Labels: skip-e2e

#3350 chore: Add `enhancement` to label for stale bot to ignore
  .github/stale.yml
Labels: skip-e2e

#3355 chore: install az-cli using pip in build-tools
  tools/build-tools.Dockerfile
Labels: skip-e2e

#3356 Clean e2e tests.
  tests/run-arm-smoke-tests.sh
  tests/scalers/artemis-helpers.ts
  tests/scalers/artemis.test.ts
Labels: skip-e2e

#3368 chore: update FOSSA key and badge
  .fossa.yml
  .github/workflows/fossa.yml
  README.md
Labels: skip-e2e

#3371 fix: remove unsupported parameter from fossa task
  .github/workflows/fossa.yml
Labels: skip-e2e

#3376 chore: e2e tests Readme
  tests/README.md
Labels: ok-to-merge

#3131 fix: unify github actions workflow using multiarch image of build-tools
  .github/workflows/pr-validation.yml
  Makefile
Labels: skip-e2e

#3338 make propagationPolicy configurable during job rollout
  CHANGELOG.md
  apis/keda/v1alpha1/scaledjob_types.go
  config/crd/bases/keda.sh_scaledjobs.yaml
  controllers/keda/scaledjob_controller.go
Labels: ok-to-merge, skip-e2e

#3395 Use go-install instead of go-get in Makefile
  CHANGELOG.md
  Makefile
Labels: skip-e2e

#3398 chore: e2e - extend timeout for cassandra & activemq tests
  tests/scalers_go/activemq/activemq_test.go
  tests/scalers_go/cassandra/cassandra_test.go
Labels: skip-e2e

#3383 feat: Introduce activationThreshold/minMetricValue for Azure scalers
  .github/workflows/main-build.yml
  .github/workflows/nightly-e2e.yml
  .github/workflows/pr-e2e.yml
  go.mod
  go.sum
  pkg/scalers/azure/azure_blob.go
  pkg/scalers/azure/azure_data_explorer.go
  pkg/scalers/azure_app_insights_scaler.go
  pkg/scalers/azure_app_insights_scaler_test.go
  pkg/scalers/azure_blob_scaler.go
  pkg/scalers/azure_blob_scaler_test.go
  pkg/scalers/azure_data_explorer_scaler.go
  pkg/scalers/azure_data_explorer_scaler_test.go
  pkg/scalers/azure_eventhub_scaler.go
  pkg/scalers/azure_eventhub_scaler_test.go
  pkg/scalers/azure_log_analytics_scaler.go
  pkg/scalers/azure_log_analytics_scaler_test.go
  pkg/scalers/azure_monitor_scaler.go
  pkg/scalers/azure_monitor_scaler_test.go
  pkg/scalers/azure_pipelines_scaler.go
  pkg/scalers/azure_pipelines_scaler_test.go
  pkg/scalers/azure_queue_scaler.go
  pkg/scalers/azure_queue_scaler_test.go
  pkg/scalers/azure_servicebus_scaler.go
  pkg/scalers/azure_servicebus_scaler_test.go
  tests/.env
  tests/helper/helper.go
  tests/internals/idle_replicas/idle_replicas_test.go
  tests/internals/pause_scaling/pause_scaling_test.go
  tests/internals/restore_original/restore_original_test.go
  tests/run-all.sh
  tests/scalers/azure-app-insights.test.ts
  tests/scalers/azure-pipelines.test.ts
  tests/scalers_go/azure_application_insights/azure_application_insights_test.go
  tests/scalers_go/azure_blob/azure_blob_test.go
  tests/scalers_go/azure_data_explorer/azure_data_explorer_test.go
  tests/scalers_go/azure_log_analytics/azure_log_analytics_test.go
  tests/scalers_go/azure_pipelines/azure_pipelines_test.go
  tests/scalers_go/azure_queue/azure_queue_test.go
  tests/scalers_go/azure_service_bus_queue/azure_service_bus_queue_test.go
  tests/scalers_go/azure_service_bus_topic/azure_service_bus_topic_test.go
  tests/secret-providers/azure_keyvault/azure_keyvault_test.go
  tests/secret-providers/azure_workload_identity/azure_workload_identity_test.go
  tests/secret-providers/azure_workload_identity_user_assigned/azure_workload_identity_user_assigned_test.go
  tests/secret-providers/trigger_auth_secret/trigger_auth_secret_test.go
Labels: skip-e2e

#3403 feat: Introduce activationThreshold/minMetricValue for Huawei Scaler
  pkg/scalers/huawei_cloudeye_scaler.go
  pkg/scalers/huawei_cloudeye_scaler_test.go
Labels: skip-e2e

#3404 feat: Introduce activationThreshold/minMetricValue for IBM Scaler
  pkg/scalers/ibmmq_scaler.go
  pkg/scalers/ibmmq_scaler_test.go
Labels: skip-e2e

#3409 feat: Introduce activationThreshold/minMetricValue for Liiklus and Openstack metrics Scalers
  pkg/scalers/liiklus_scaler.go
  pkg/scalers/liiklus_scaler_test.go
  pkg/scalers/openstack_metrics_scaler.go
  pkg/scalers/openstack_metrics_scaler_test.go
Labels: skip-e2e

#3444 chore: Use golang version as tag for build-tools and bump it
  Makefile
  tools/build-tools.Dockerfile
Labels: skip-e2e
