Repository kedacore/keda, pull requests merged in 2024-01, with the labels that each got.

#5018 chore: Increase minimum supported Kubernetes version for KEDA v2.13
  pkg/util/welcome.go
Labels: skip-e2e

#5363 chore: Automatically close stale PRs
  .github/stale.yml
Labels: skip-e2e

#4652 feat: Automatically apply label for review + PR comment for draft PRs
  .github/workflows/pr-welcome.yml
Labels: skip-e2e, requires-pr-review

#5372 chore: fix jetstream flaky test
  pkg/scalers/nats_jetstream_scaler_test.go
Labels: skip-e2e, requires-pr-review

#5370 chore: bump Go to 1.21.6
  .github/workflows/main-build.yml
  .github/workflows/pr-e2e.yml
  .github/workflows/pr-validation.yml
  .github/workflows/release-build.yml
  .github/workflows/static-analysis-codeql.yml
  .github/workflows/template-main-e2e-test.yml
  Dockerfile
  Dockerfile.adapter
  Dockerfile.webhooks
Labels: requires-pr-review

#5376 fix: PR bot fails due to mixing action triggers
  .github/workflows/pr-welcome.yml
Labels: skip-e2e, requires-pr-review

#5360 docs: Changelog & bug template for 2.13.0 release
  .github/ISSUE_TEMPLATE/3_bug_report.yml
  CHANGELOG.md
Labels: skip-e2e, requires-pr-review

#5378 chore: Tweak PR bot logic
  .github/workflows/pr-welcome.yml
Labels: skip-e2e

#5380 fix: PR Bot has malformed workflow manifest
  .github/workflows/pr-welcome.yml
Labels: skip-e2e

#5396 chore: Add a comment for az pipelines magic string
  pkg/scalers/azure_pipelines_scaler.go
Labels: skip-e2e

#5399 chore: bump golangci-lint to 1.55.2
  .devcontainer/Dockerfile
  .github/workflows/pr-validation.yml
  CONTRIBUTING.md
Labels: skip-e2e

#5402 doc: remind about dependency version bumps before releases
  .github/ISSUE_TEMPLATE/4_release_tracker.md
Labels: skip-e2e

#5398 chore: Changelog cleanup
  CHANGELOG.md
Labels: skip-e2e

#5405 Set LeaderElectionNamespace to PodNamespace
  CHANGELOG.md
  cmd/operator/main.go
Labels: skip-e2e

#5412 chore: Introduce KEDA v2.13 and estimate v2.16 in roadmap
  ROADMAP.md
Labels: skip-e2e

#5413 chore: Improve new features in v2.13.0 changelog
  CHANGELOG.md
Labels: skip-e2e

#5437 Fix typo on makefile
  Makefile
Labels: skip-e2e

#5439 Edit e2e test YAML before merging #5436
  .github/workflows/pr-e2e.yml
  .github/workflows/template-main-e2e-test.yml
  CHANGELOG.md
Labels: skip-e2e
