Repository kedacore/keda, pull requests merged in 2025-08, with the labels that each got.

#6914 fix: eliminate race conditions in NSQ scaler tests by using separate mock servers
  pkg/scalers/nsq_scaler_test.go
Labels: skip-e2e

#6866 refactor gcp pubsub scaler
  CHANGELOG.md
  pkg/scalers/gcp/gcp_stackdriver_client.go
  pkg/scalers/gcp/gcp_stackdriver_client_test.go
  pkg/scalers/gcp_pubsub_scaler.go
  pkg/scalers/gcp_pubsub_scaler_test.go
Labels: ok-to-merge

#6848 refactor pulsar scaler
  pkg/scalers/pulsar_scaler.go
  pkg/scalers/pulsar_scaler_test.go
Labels: ok-to-merge

#6546 New Solace Direct Messaging Scaler
  CHANGELOG.md
  pkg/scalers/solace_dm_scaler.go
  pkg/scalers/solace_dm_scaler_test.go
  pkg/scaling/scalers_builder.go
  tests/scalers/solace/direct-messaging/solace_dm_test.go
Labels: ok-to-merge

#6888 fix: fixed cron scaler to return zero metric value by default
  CHANGELOG.md
  pkg/scalers/cron_scaler.go
  pkg/scalers/cron_scaler_test.go
Labels: ok-to-merge, skip-e2e

#6930 fix: prevent e2e test reset when adding non-skip labels
  .github/workflows/pr-e2e-checker.yml
Labels: skip-e2e

#6990 Fix waitfordeploymentreplicareadycount duration logs
  tests/README.md
  tests/internals/fallback/fallback_test.go
  tests/internals/global_custom_ca/global_custom_ca_test.go
  tests/internals/polling_cooldown_so/polling_cooldown_so_test.go
  tests/internals/replica_update_so/replica_update_so_test.go
  tests/internals/scaling_modifiers/scaling_modifiers_test.go
  tests/internals/trigger_update_so/trigger_update_so_test.go
  tests/internals/update_ta/update_ta_test.go
  tests/scalers/aws/aws_managed_prometheus/aws_managed_prometheus_test.go
  tests/scalers/aws/aws_managed_prometheus_pod_identity/aws_managed_prometheus_pod_identity_test.go
  tests/scalers/beanstalkd/beanstalkd_test.go
  tests/scalers/cron/cron_test.go
  tests/scalers/datadog/datadog_api/datadog_api_test.go
  tests/scalers/dynatrace/dynatrace_test.go
  tests/scalers/gcp/gcp_cloud_tasks/gcp_cloud_tasks_test.go
  tests/scalers/gcp/gcp_cloud_tasks_workload_identity/gcp_cloud_tasks_workload_identity_test.go
  tests/scalers/gcp/gcp_prometheus_workload_identity/gcp_prometheus_workload_identity_test.go
  tests/scalers/gcp/gcp_pubsub/gcp_pubsub_test.go
  tests/scalers/kubernetes_workload/kubernetes_workload_test.go
  tests/scalers/metrics_api/metrics_api_test.go
  tests/scalers/mysql/mysql_test.go
  tests/scalers/redis/redis_standalone_streams_lag/redis_standalone_streams_lag_test.go
  tests/scalers/splunk/splunk_test.go
  tests/scalers/sumologic/sumologic_test.go
  tests/secret-providers/trigger_auth_bound_service_account_token/trigger_auth_bound_service_account_token_test.go
  tests/sequential/datadog_dca/datadog_dca_test.go
Labels: ok-to-merge, skip-e2e

#6971 Refactor openstack metric scaler
  pkg/scalers/openstack_metrics_scaler.go
  pkg/scalers/openstack_metrics_scaler_test.go
Labels: ok-to-merge

#6997 fix: parse timeout config as milliseconds instead of seconds
  CHANGELOG.md
  pkg/scalers/prometheus_scaler.go
  pkg/scalers/rabbitmq_scaler.go
  pkg/scalers/scalersconfig/typed_config.go
  pkg/scalers/scalersconfig/typed_config_test.go
Labels: ok-to-merge

#6901 Add support for pausing scale in annotation
  CHANGELOG.md
  apis/eventing/v1alpha1/zz_generated.deepcopy.go
  apis/keda/v1alpha1/scaledobject_types.go
  apis/keda/v1alpha1/zz_generated.deepcopy.go
  controllers/keda/hpa.go
  controllers/keda/scaledobject_controller.go
  controllers/keda/scaledobject_controller_test.go
  controllers/keda/util/predicate.go
  pkg/scaling/executor/scale_scaledobjects.go
  pkg/scaling/executor/scale_scaledobjects_test.go
  tests/internals/pause_scale_in/pause_scale_in_test.go
Labels: ok-to-merge
