Repository kedacore/keda, pull requests merged in 2025-10, with the labels that each got.

#7150 ci: clear some disk space for PR validation step
  .github/workflows/pr-validation.yml
Labels: ok-to-merge, skip-e2e

#7155 update release schedule and estimations
  ROADMAP.md
Labels: skip-e2e

#7159 fix: update release tracker checklist for changelog preparation
  .github/ISSUE_TEMPLATE/4_release_tracker.md
Labels: skip-e2e

#7109 Add support for CloudWatch extended statistics (percentiles, trimmed mean, etc.) in the CloudWatch scaler to enable more advanced metric queries
  CHANGELOG.md
  pkg/scalers/aws_cloudwatch_scaler.go
  pkg/scalers/aws_cloudwatch_scaler_test.go
  tests/scalers/aws/aws_cloudwatch_metric_stat/aws_cloudwatch_metric_stat_test.go
Labels: ok-to-merge

#7162 chore: release tracker update 3
  .github/ISSUE_TEMPLATE/4_release_tracker.md
Labels: skip-e2e
